# Copyright 2026 OmniLink
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""The PX4 x500 package (projects/robots/px4/x500) and its showcase world.

Generated by make_x500.py from PX4-gazebo-models; these pin what the rest of
the tree relies on: every referenced asset is present, the names the Mavic
bridge looks up exist, the upstream logos did not ship, the licence trail is
there, and the showcase world declares what the airframe needs to fly.
"""
from __future__ import annotations

import importlib.util
import json
import re
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PKG = REPO / "projects/robots/px4/x500"
URDF = PKG / "urdf/x500.urdf"
WORLD = REPO / "projects/samples/demos/worlds/showcase/x500_arena.omniworld"


def _urdf():
    return ET.parse(URDF).getroot()


def test_every_mesh_and_texture_the_urdf_names_exists():
    root = _urdf()
    refs = [m.get("filename") for m in root.iter("mesh")] + [t.get("filename") for t in root.iter("texture")]
    assert refs and all((URDF.parent / r).resolve().is_file() for r in refs), refs


def test_the_bridge_finds_its_joints_and_sensors():
    root = _urdf()
    joints = {j.get("name") for j in root.findall("joint")}
    assert {"front left propeller", "front right propeller", "rear left propeller",
            "rear right propeller", "camera yaw", "camera pitch", "camera roll"} <= joints
    assert {s.get("name") for s in root.iter("sensor")} >= {"camera", "inertial unit", "gps"}


def test_no_upstream_logo_ships():
    names = {p.name.lower() for p in PKG.rglob("*")}
    assert not names & {"nxp.png", "rd.png", "nxp-hgd-cf.dae"}
    text = URDF.read_text(encoding="utf-8").lower()
    assert "nxp.png" not in text and "rd.png" not in text


def test_licence_trail_is_bsd3_from_the_pinned_commit():
    lic = (PKG / "LICENSE.upstream").read_text(encoding="utf-8")
    assert "BSD 3-Clause" in lic and "Rudis Laboratories" in lic
    prov = (PKG / "PROVENANCE.md").read_text(encoding="utf-8")
    assert "d679f3a77999002f01f7e404fc365d124be15221" in prov


def test_rotor_discs_start_invisible():
    for m in _urdf().findall("material"):
        if m.get("name") == "x500_prop_disc":
            assert m.find("color").get("rgba").split()[3] == "0"
            return
    raise AssertionError("x500_prop_disc material missing")


def test_the_showcase_world_declares_what_the_airframe_needs():
    text = WORLD.read_text(encoding="utf-8")
    assert "newtonCompoundColliders TRUE" in text
    assert 'url "../../../../robots/px4/x500/urdf/x500.urdf"' in text
    assert "OMNISIM_URDF_USE_SENSORS=1" in text and "MODELLED" in text
    raw = re.search(r'customData "(.*)"\n', text).group(1).replace('\\"', '"')
    spec = importlib.util.spec_from_file_location(
        "mavic_dynamics_pkg", REPO / "projects/samples/demos/controllers/mavic_omnilink_bridge/mavic_dynamics.py")
    md = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(md)
    af = md.airframe_from_custom_data(raw)
    assert af and af["rotor_disc_material"] == "x500_prop_disc"
    assert af["wind"]["seed"] == 7 and af["control"]["HEADING_HOLD"] == 1
    json.dumps(af)
